server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://192.168.1.35:3306/rp_garbage?characterEncoding=UTF-8
    username: root
    password: Runpu2018
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
